travis:
  secure:
    BINSTAR_TOKEN: HN2hUcWmRxMFbQnypGY+zGJyg0iuAp6OW+yWJphqiT3/+dGyMAOwtvGLemrhHmXcK49jvCPnPHBLVpQnrqAHKjgeQZSy5XOfJDvvREDbyLZ0MAuXEQJBlBOGqR4uoxPVF5LK0DEwNtbrqQXQF/vb+XPamSJbcSljBxJYkB84AMLEM/EYhfSqaRhLp//9WucARvqBWRiEtAxrdVtBxj0B2SokziMEpf28446gqqe3lnZfKxvcKQvFRymJoam7tdLODDQgU5P2RfJRvNpjJfps0wG+V5VdRixMvvJRSPUFjItyfh61YDPyscdzfefRgvTX2HUW6bjiC6v7/K+tzMmsuB5Q3cNC2q/AK0vgp771YbzSzgkJjD17p++/ilg/48jSz+ZPXiLdOZAkorFIwAf0JFrhrG/wKx6NMIGe3ner3/QFGCEOs+0migWFAgdOmBEWCmTMuQr5wew3BqzqxL4FMpn4yRHZ+VpPQyPnPGNW+UbPNr0IxUbf8EKCWKZKvlcXsHAMjlE1gMtYAyg/yPEmg8rvioGyPj+HYXNrRug0PCHYgqwQeZVZgU2NhfAYgHZ/ST7qyAhTQKknv2gpZM/AhjADr49NMwXfVSpI6k5f6KSwFs+VMJXd05vhg2kDHqa4171sOHfOstNDIgT8GhunS9SLBWtWobZ8OBsA/BPf3+o=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
