appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: TeFLJTn8aEzWjFzzgU4rxAujXZ9H2Od2XnV9EPoit+vYE/IDGFUeLsVNFaaLrfRJdtL7j7ak+ELPUEt6dhKtpZXIhyd0h3vAhcZEMCHmJuAaVjm6k2kWC5xHEMz9QJdP/K2LjPx7HZ8n29TJulkdl2oQawJ71RQxDL0bvu4COALcEwXGNmVNKpCT+Z/YouASnTmXN038GQZwWpEqBXA77l6nB8IjARkrsyPUhiRW1lsxtouV63ymmin5UGW6riP4a//0mutCkQ0AZlr8iKbTS3Rk7mfBDgVnfNFF+eZR2pQRnyLILWQoH5she2B1mx8P/5zq1rlL2jy0ijIsRr1au5WEKQMdLMKFA0Z7X/Hu5fmdBtn2j8oJqhxufcKTRzQoti0/jNX7nxeNZUvzClYWOH1uz0S287Kj/Y+Kd4K+PCxy6ISgJqtAekNAT/kYnYn+/Xb4PpT26Op19dgbx8WOarhf//V+g45f4g1VjYPmshChwAWRUs6cFwLkB+G5rwdaNqJurtqHZKPw1TUEFPZNZTAcP3Z5H7kVR8gcqQIAsdO2X4w30EhNiuyI1E4BtgCTxKxlLvJbtKn7rqVVqPdLuKZk44ru94OhO1vdj8KLZqEYahgkfLJXpK4jd+CFloX0l9qhy/QdO1EnpNFhlYdttKjgRXuUWBqG6q2fmgU4rCk=
conda_forge_output_validation: true
